package Campus;


/**
* Campus/_GestionCampusStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Campus.idl
* lundi 8 d�cembre 2025 11 h 06 WAT
*/

public class _GestionCampusStub extends org.omg.CORBA.portable.ObjectImpl implements Campus.GestionCampus
{


  //  CHAMBRES
  public int ajouterChambre (String numero, String type_chambre, int capacite, double prix_par_jour, String equipements, String description, String statut)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("ajouterChambre", true);
                $out.write_string (numero);
                $out.write_string (type_chambre);
                $out.write_long (capacite);
                $out.write_double (prix_par_jour);
                $out.write_string (equipements);
                $out.write_string (description);
                $out.write_string (statut);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return ajouterChambre (numero, type_chambre, capacite, prix_par_jour, equipements, description, statut        );
            } finally {
                _releaseReply ($in);
            }
  } // ajouterChambre

  public void modifierChambre (int id, String numero, String type_chambre, int capacite, double prix_par_jour, String equipements, String description)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("modifierChambre", true);
                $out.write_long (id);
                $out.write_string (numero);
                $out.write_string (type_chambre);
                $out.write_long (capacite);
                $out.write_double (prix_par_jour);
                $out.write_string (equipements);
                $out.write_string (description);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                modifierChambre (id, numero, type_chambre, capacite, prix_par_jour, equipements, description        );
            } finally {
                _releaseReply ($in);
            }
  } // modifierChambre

  public void supprimerChambre (int id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("supprimerChambre", true);
                $out.write_long (id);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                supprimerChambre (id        );
            } finally {
                _releaseReply ($in);
            }
  } // supprimerChambre

  public Campus.Chambre[] listerToutesChambres ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listerToutesChambres", true);
                $in = _invoke ($out);
                Campus.Chambre $result[] = Campus.ListeChambresHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listerToutesChambres (        );
            } finally {
                _releaseReply ($in);
            }
  } // listerToutesChambres

  public Campus.Chambre rechercherChambre (int id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("rechercherChambre", true);
                $out.write_long (id);
                $in = _invoke ($out);
                Campus.Chambre $result = Campus.ChambreHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return rechercherChambre (id        );
            } finally {
                _releaseReply ($in);
            }
  } // rechercherChambre


  // Mise à jour du statut de la chambre (très utile !)
  public void majStatutChambre (int chambre_id, String nouveau_statut)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("majStatutChambre", true);
                $out.write_long (chambre_id);
                $out.write_string (nouveau_statut);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                majStatutChambre (chambre_id, nouveau_statut        );
            } finally {
                _releaseReply ($in);
            }
  } // majStatutChambre


  //CLIENTS
  public int creerClient (String nom, String email, String telephone, String type_client, String organisation)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("creerClient", true);
                $out.write_string (nom);
                $out.write_string (email);
                $out.write_string (telephone);
                $out.write_string (type_client);
                $out.write_string (organisation);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return creerClient (nom, email, telephone, type_client, organisation        );
            } finally {
                _releaseReply ($in);
            }
  } // creerClient

  public void modifierClient (int id, String nom, String email, String telephone, String type_client, String organisation)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("modifierClient", true);
                $out.write_long (id);
                $out.write_string (nom);
                $out.write_string (email);
                $out.write_string (telephone);
                $out.write_string (type_client);
                $out.write_string (organisation);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                modifierClient (id, nom, email, telephone, type_client, organisation        );
            } finally {
                _releaseReply ($in);
            }
  } // modifierClient

  public void supprimerClient (int id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("supprimerClient", true);
                $out.write_long (id);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                supprimerClient (id        );
            } finally {
                _releaseReply ($in);
            }
  } // supprimerClient

  public Campus.Client rechercherClient (int id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("rechercherClient", true);
                $out.write_long (id);
                $in = _invoke ($out);
                Campus.Client $result = Campus.ClientHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return rechercherClient (id        );
            } finally {
                _releaseReply ($in);
            }
  } // rechercherClient

  public Campus.Client[] listerTousClients ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listerTousClients", true);
                $in = _invoke ($out);
                Campus.Client $result[] = Campus.ListeClientsHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listerTousClients (        );
            } finally {
                _releaseReply ($in);
            }
  } // listerTousClients


  // R�0SERVATIONS
  public int creerReservation (int client_id, int chambre_id, String date_debut, String date_fin)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("creerReservation", true);
                $out.write_long (client_id);
                $out.write_long (chambre_id);
                $out.write_string (date_debut);
                $out.write_string (date_fin);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return creerReservation (client_id, chambre_id, date_debut, date_fin        );
            } finally {
                _releaseReply ($in);
            }
  } // creerReservation

  public void modifierReservation (int reservation_id, int client_id, int chambre_id, String date_debut, String date_fin)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("modifierReservation", true);
                $out.write_long (reservation_id);
                $out.write_long (client_id);
                $out.write_long (chambre_id);
                $out.write_string (date_debut);
                $out.write_string (date_fin);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                modifierReservation (reservation_id, client_id, chambre_id, date_debut, date_fin        );
            } finally {
                _releaseReply ($in);
            }
  } // modifierReservation

  public void annulerReservation (int reservation_id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("annulerReservation", true);
                $out.write_long (reservation_id);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                annulerReservation (reservation_id        );
            } finally {
                _releaseReply ($in);
            }
  } // annulerReservation


  //Confirmation de réservation
  public boolean majStatutReservation (int reservation_id, String nouveau_statut)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("majStatutReservation", true);
                $out.write_long (reservation_id);
                $out.write_string (nouveau_statut);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return majStatutReservation (reservation_id, nouveau_statut        );
            } finally {
                _releaseReply ($in);
            }
  } // majStatutReservation


  // Récupérer toutes les réservations d'un client
  public Campus.Reservation[] historiqueClient (int client_id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("historiqueClient", true);
                $out.write_long (client_id);
                $in = _invoke ($out);
                Campus.Reservation $result[] = Campus.ListeReservationsHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return historiqueClient (client_id        );
            } finally {
                _releaseReply ($in);
            }
  } // historiqueClient


  // Récupérer toutes les réservations d'une chambre
  public Campus.Reservation[] reservationsChambre (int chambre_id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("reservationsChambre", true);
                $out.write_long (chambre_id);
                $in = _invoke ($out);
                Campus.Reservation $result[] = Campus.ListeReservationsHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return reservationsChambre (chambre_id        );
            } finally {
                _releaseReply ($in);
            }
  } // reservationsChambre

  public Campus.Reservation[] toutesLesReservations ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("toutesLesReservations", true);
                $in = _invoke ($out);
                Campus.Reservation $result[] = Campus.ListeReservationsHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return toutesLesReservations (        );
            } finally {
                _releaseReply ($in);
            }
  } // toutesLesReservations

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Campus/GestionCampus:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _GestionCampusStub
