package Campus;

/**
* Campus/ChambreHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Campus.idl
* lundi 8 décembre 2025 11 h 01 WAT
*/

public final class ChambreHolder implements org.omg.CORBA.portable.Streamable
{
  public Campus.Chambre value = null;

  public ChambreHolder ()
  {
  }

  public ChambreHolder (Campus.Chambre initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Campus.ChambreHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Campus.ChambreHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Campus.ChambreHelper.type ();
  }

}
