package Campus;


/**
* Campus/Chambre.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Campus.idl
* lundi 8 d�cembre 2025 11 h 01 WAT
*/

public final class Chambre implements org.omg.CORBA.portable.IDLEntity
{
  public int chambre_id = (int)0;
  public String numero = null;
  public String type_chambre = null;
  public int capacite = (int)0;
  public double prix_par_jour = (double)0;
  public String equipements = null;
  public String statut = null;

  // Disponible, Réservée, Occupée, Maintenance...
  public String description = null;

  public Chambre ()
  {
  } // ctor

  public Chambre (int _chambre_id, String _numero, String _type_chambre, int _capacite, double _prix_par_jour, String _equipements, String _statut, String _description)
  {
    chambre_id = _chambre_id;
    numero = _numero;
    type_chambre = _type_chambre;
    capacite = _capacite;
    prix_par_jour = _prix_par_jour;
    equipements = _equipements;
    statut = _statut;
    description = _description;
  } // ctor

} // class Chambre
