package Campus;


/**
* Campus/Client.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Campus.idl
* lundi 8 décembre 2025 11 h 06 WAT
*/

public final class Client implements org.omg.CORBA.portable.IDLEntity
{
  public int client_id = (int)0;
  public String nom = null;
  public String email = null;
  public String telephone = null;
  public String type_client = null;
  public String organisation = null;

  public Client ()
  {
  } // ctor

  public Client (int _client_id, String _nom, String _email, String _telephone, String _type_client, String _organisation)
  {
    client_id = _client_id;
    nom = _nom;
    email = _email;
    telephone = _telephone;
    type_client = _type_client;
    organisation = _organisation;
  } // ctor

} // class Client
