package Campus;

/**
* Campus/ClientHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Campus.idl
* lundi 8 décembre 2025 11 h 06 WAT
*/

public final class ClientHolder implements org.omg.CORBA.portable.Streamable
{
  public Campus.Client value = null;

  public ClientHolder ()
  {
  }

  public ClientHolder (Campus.Client initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Campus.ClientHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Campus.ClientHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Campus.ClientHelper.type ();
  }

}
