package Campus;


/**
* Campus/GestionCampusPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Campus.idl
* lundi 8 d�cembre 2025 11 h 06 WAT
*/

public abstract class GestionCampusPOA extends org.omg.PortableServer.Servant
 implements Campus.GestionCampusOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("ajouterChambre", new java.lang.Integer (0));
    _methods.put ("modifierChambre", new java.lang.Integer (1));
    _methods.put ("supprimerChambre", new java.lang.Integer (2));
    _methods.put ("listerToutesChambres", new java.lang.Integer (3));
    _methods.put ("rechercherChambre", new java.lang.Integer (4));
    _methods.put ("majStatutChambre", new java.lang.Integer (5));
    _methods.put ("creerClient", new java.lang.Integer (6));
    _methods.put ("modifierClient", new java.lang.Integer (7));
    _methods.put ("supprimerClient", new java.lang.Integer (8));
    _methods.put ("rechercherClient", new java.lang.Integer (9));
    _methods.put ("listerTousClients", new java.lang.Integer (10));
    _methods.put ("creerReservation", new java.lang.Integer (11));
    _methods.put ("modifierReservation", new java.lang.Integer (12));
    _methods.put ("annulerReservation", new java.lang.Integer (13));
    _methods.put ("majStatutReservation", new java.lang.Integer (14));
    _methods.put ("historiqueClient", new java.lang.Integer (15));
    _methods.put ("reservationsChambre", new java.lang.Integer (16));
    _methods.put ("toutesLesReservations", new java.lang.Integer (17));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  //  CHAMBRES
       case 0:  // Campus/GestionCampus/ajouterChambre
       {
         String numero = in.read_string ();
         String type_chambre = in.read_string ();
         int capacite = in.read_long ();
         double prix_par_jour = in.read_double ();
         String equipements = in.read_string ();
         String description = in.read_string ();
         String statut = in.read_string ();
         int $result = (int)0;
         $result = this.ajouterChambre (numero, type_chambre, capacite, prix_par_jour, equipements, description, statut);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // Campus/GestionCampus/modifierChambre
       {
         int id = in.read_long ();
         String numero = in.read_string ();
         String type_chambre = in.read_string ();
         int capacite = in.read_long ();
         double prix_par_jour = in.read_double ();
         String equipements = in.read_string ();
         String description = in.read_string ();
         this.modifierChambre (id, numero, type_chambre, capacite, prix_par_jour, equipements, description);
         out = $rh.createReply();
         break;
       }

       case 2:  // Campus/GestionCampus/supprimerChambre
       {
         int id = in.read_long ();
         this.supprimerChambre (id);
         out = $rh.createReply();
         break;
       }

       case 3:  // Campus/GestionCampus/listerToutesChambres
       {
         Campus.Chambre $result[] = null;
         $result = this.listerToutesChambres ();
         out = $rh.createReply();
         Campus.ListeChambresHelper.write (out, $result);
         break;
       }

       case 4:  // Campus/GestionCampus/rechercherChambre
       {
         int id = in.read_long ();
         Campus.Chambre $result = null;
         $result = this.rechercherChambre (id);
         out = $rh.createReply();
         Campus.ChambreHelper.write (out, $result);
         break;
       }


  // Mise à jour du statut de la chambre (très utile !)
       case 5:  // Campus/GestionCampus/majStatutChambre
       {
         int chambre_id = in.read_long ();
         String nouveau_statut = in.read_string ();
         this.majStatutChambre (chambre_id, nouveau_statut);
         out = $rh.createReply();
         break;
       }


  //CLIENTS
       case 6:  // Campus/GestionCampus/creerClient
       {
         String nom = in.read_string ();
         String email = in.read_string ();
         String telephone = in.read_string ();
         String type_client = in.read_string ();
         String organisation = in.read_string ();
         int $result = (int)0;
         $result = this.creerClient (nom, email, telephone, type_client, organisation);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 7:  // Campus/GestionCampus/modifierClient
       {
         int id = in.read_long ();
         String nom = in.read_string ();
         String email = in.read_string ();
         String telephone = in.read_string ();
         String type_client = in.read_string ();
         String organisation = in.read_string ();
         this.modifierClient (id, nom, email, telephone, type_client, organisation);
         out = $rh.createReply();
         break;
       }

       case 8:  // Campus/GestionCampus/supprimerClient
       {
         int id = in.read_long ();
         this.supprimerClient (id);
         out = $rh.createReply();
         break;
       }

       case 9:  // Campus/GestionCampus/rechercherClient
       {
         int id = in.read_long ();
         Campus.Client $result = null;
         $result = this.rechercherClient (id);
         out = $rh.createReply();
         Campus.ClientHelper.write (out, $result);
         break;
       }

       case 10:  // Campus/GestionCampus/listerTousClients
       {
         Campus.Client $result[] = null;
         $result = this.listerTousClients ();
         out = $rh.createReply();
         Campus.ListeClientsHelper.write (out, $result);
         break;
       }


  // R�0SERVATIONS
       case 11:  // Campus/GestionCampus/creerReservation
       {
         int client_id = in.read_long ();
         int chambre_id = in.read_long ();
         String date_debut = in.read_string ();
         String date_fin = in.read_string ();
         int $result = (int)0;
         $result = this.creerReservation (client_id, chambre_id, date_debut, date_fin);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 12:  // Campus/GestionCampus/modifierReservation
       {
         int reservation_id = in.read_long ();
         int client_id = in.read_long ();
         int chambre_id = in.read_long ();
         String date_debut = in.read_string ();
         String date_fin = in.read_string ();
         this.modifierReservation (reservation_id, client_id, chambre_id, date_debut, date_fin);
         out = $rh.createReply();
         break;
       }

       case 13:  // Campus/GestionCampus/annulerReservation
       {
         int reservation_id = in.read_long ();
         this.annulerReservation (reservation_id);
         out = $rh.createReply();
         break;
       }


  //Confirmation de réservation
       case 14:  // Campus/GestionCampus/majStatutReservation
       {
         int reservation_id = in.read_long ();
         String nouveau_statut = in.read_string ();
         boolean $result = false;
         $result = this.majStatutReservation (reservation_id, nouveau_statut);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }


  // Récupérer toutes les réservations d'un client
       case 15:  // Campus/GestionCampus/historiqueClient
       {
         int client_id = in.read_long ();
         Campus.Reservation $result[] = null;
         $result = this.historiqueClient (client_id);
         out = $rh.createReply();
         Campus.ListeReservationsHelper.write (out, $result);
         break;
       }


  // Récupérer toutes les réservations d'une chambre
       case 16:  // Campus/GestionCampus/reservationsChambre
       {
         int chambre_id = in.read_long ();
         Campus.Reservation $result[] = null;
         $result = this.reservationsChambre (chambre_id);
         out = $rh.createReply();
         Campus.ListeReservationsHelper.write (out, $result);
         break;
       }

       case 17:  // Campus/GestionCampus/toutesLesReservations
       {
         Campus.Reservation $result[] = null;
         $result = this.toutesLesReservations ();
         out = $rh.createReply();
         Campus.ListeReservationsHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Campus/GestionCampus:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GestionCampus _this() 
  {
    return GestionCampusHelper.narrow(
    super._this_object());
  }

  public GestionCampus _this(org.omg.CORBA.ORB orb) 
  {
    return GestionCampusHelper.narrow(
    super._this_object(orb));
  }


} // class GestionCampusPOA
