package Campus;


/**
* Campus/GestionCampus.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Campus.idl
* lundi 8 décembre 2025 11 h 01 WAT
*/

public interface GestionCampus extends GestionCampusOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionCampus
