package Campus;


/**
* Campus/GestionCampusOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Campus.idl
* lundi 8 d�cembre 2025 11 h 06 WAT
*/

public interface GestionCampusOperations 
{

  //  CHAMBRES
  int ajouterChambre (String numero, String type_chambre, int capacite, double prix_par_jour, String equipements, String description, String statut);
  void modifierChambre (int id, String numero, String type_chambre, int capacite, double prix_par_jour, String equipements, String description);
  void supprimerChambre (int id);
  Campus.Chambre[] listerToutesChambres ();
  Campus.Chambre rechercherChambre (int id);

  // Mise à jour du statut de la chambre (très utile !)
  void majStatutChambre (int chambre_id, String nouveau_statut);

  //CLIENTS
  int creerClient (String nom, String email, String telephone, String type_client, String organisation);
  void modifierClient (int id, String nom, String email, String telephone, String type_client, String organisation);
  void supprimerClient (int id);
  Campus.Client rechercherClient (int id);
  Campus.Client[] listerTousClients ();

  // R�0SERVATIONS
  int creerReservation (int client_id, int chambre_id, String date_debut, String date_fin);
  void modifierReservation (int reservation_id, int client_id, int chambre_id, String date_debut, String date_fin);
  void annulerReservation (int reservation_id);

  //Confirmation de réservation
  boolean majStatutReservation (int reservation_id, String nouveau_statut);

  // Récupérer toutes les réservations d'un client
  Campus.Reservation[] historiqueClient (int client_id);

  // Récupérer toutes les réservations d'une chambre
  Campus.Reservation[] reservationsChambre (int chambre_id);
  Campus.Reservation[] toutesLesReservations ();
} // interface GestionCampusOperations
