package Campus;

/**
* Campus/GestionCampusHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Campus.idl
* lundi 8 décembre 2025 11 h 06 WAT
*/

public final class GestionCampusHolder implements org.omg.CORBA.portable.Streamable
{
  public Campus.GestionCampus value = null;

  public GestionCampusHolder ()
  {
  }

  public GestionCampusHolder (Campus.GestionCampus initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Campus.GestionCampusHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Campus.GestionCampusHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Campus.GestionCampusHelper.type ();
  }

}
