package Campus;


/**
* Campus/ListeReservationsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Campus.idl
* lundi 8 décembre 2025 11 h 01 WAT
*/

abstract public class ListeReservationsHelper
{
  private static String  _id = "IDL:Campus/ListeReservations:1.0";

  public static void insert (org.omg.CORBA.Any a, Campus.Reservation[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Campus.Reservation[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = Campus.ReservationHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (Campus.ListeReservationsHelper.id (), "ListeReservations", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Campus.Reservation[] read (org.omg.CORBA.portable.InputStream istream)
  {
    Campus.Reservation value[] = null;
    int _len0 = istream.read_long ();
    value = new Campus.Reservation[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = Campus.ReservationHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Campus.Reservation[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      Campus.ReservationHelper.write (ostream, value[_i0]);
  }

}
