package Campus;


/**
* Campus/ListeReservationsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Campus.idl
* lundi 8 décembre 2025 11 h 01 WAT
*/

public final class ListeReservationsHolder implements org.omg.CORBA.portable.Streamable
{
  public Campus.Reservation value[] = null;

  public ListeReservationsHolder ()
  {
  }

  public ListeReservationsHolder (Campus.Reservation[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Campus.ListeReservationsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Campus.ListeReservationsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Campus.ListeReservationsHelper.type ();
  }

}
