package Campus;


/**
* Campus/ListeClientsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Campus.idl
* lundi 8 décembre 2025 11 h 06 WAT
*/

public final class ListeClientsHolder implements org.omg.CORBA.portable.Streamable
{
  public Campus.Client value[] = null;

  public ListeClientsHolder ()
  {
  }

  public ListeClientsHolder (Campus.Client[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Campus.ListeClientsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Campus.ListeClientsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Campus.ListeClientsHelper.type ();
  }

}
