package Campus;


/**
* Campus/ListeChambresHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Campus.idl
* lundi 8 décembre 2025 11 h 06 WAT
*/

public final class ListeChambresHolder implements org.omg.CORBA.portable.Streamable
{
  public Campus.Chambre value[] = null;

  public ListeChambresHolder ()
  {
  }

  public ListeChambresHolder (Campus.Chambre[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Campus.ListeChambresHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Campus.ListeChambresHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Campus.ListeChambresHelper.type ();
  }

}
