package Campus;


/**
* Campus/Reservation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Campus.idl
* lundi 8 décembre 2025 11 h 01 WAT
*/

public final class Reservation implements org.omg.CORBA.portable.IDLEntity
{
  public int reservation_id = (int)0;
  public int client_id = (int)0;
  public int chambre_id = (int)0;
  public String date_debut = null;

  // Format: "YYYY-MM-DD"
  public String date_fin = null;

  // Format: "YYYY-MM-DD"
  public double total = (double)0;
  public String statut = null;

  public Reservation ()
  {
  } // ctor

  public Reservation (int _reservation_id, int _client_id, int _chambre_id, String _date_debut, String _date_fin, double _total, String _statut)
  {
    reservation_id = _reservation_id;
    client_id = _client_id;
    chambre_id = _chambre_id;
    date_debut = _date_debut;
    date_fin = _date_fin;
    total = _total;
    statut = _statut;
  } // ctor

} // class Reservation
